version: "3.7"
services:

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}-nginx
    env_file: ./env/file/${ENVIRONMENT}.env
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - type: bind
        source: ./volumes/nginx/etc/nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true 
      - type: bind
        source: ./volumes/app/var/www/html
        target: /var/www/html
        read_only: true
    working_dir: /var/www/html
    networks:
      frontend:
        aliases:
          - nginx

  app:
    build: ./dockerfiles/app
    container_name: ${PROJECT_NAME}-web
    env_file: ./env/file/${ENVIRONMENT}.env
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - type: bind
        source: ./volumes/app/var/www/html
        target: /var/www/html
      - type: bind
        source: ${PROJECT_HOME_SRC}/configuration.php
        target: ${DOCUMENT_ROOT}/configuration.php
 
    networks:
      frontend:
        aliases:
          - my-app.test
          - app

  db:
    image: mariadb:latest
    container_name: ${PROJECT_NAME}-db
    env_file: ./env/file/${ENVIRONMENT}.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      frontend:
        aliases:
          - mariadb
    ports:
      - 3306:3306

networks:
  frontend:
    name: ${PROJECT_NAME}_frontend

volumes:
  db-data:
